name: Containerized App Stack deployment with Terraform

on:
  workflow_dispatch:
    inputs:
      terra_op:
        description: "Select Terraform operation to perform"
        required: true
        type: choice
        options:
          - plan
          - check
          - apply
          - destroy


jobs:
  Build_and_Deploy:
    runs-on: ubuntu-latest
    env:
    # TF_VAR is the prefix used to set Terraform variables via environment variables
      TF_VAR_tf_s3_bucket: ${{ secrets.TF_STATE_BUCKET }}
      TF_VAR_ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
      TF_VAR_vpc_id: ${{ secrets.VPC_ID }}
      TF_VAR_my_ip_cidr: ${{ secrets.MY_IP_CIDR }}

      TF_VAR_region: ${{ vars.AWS_REGION }}
      TF_VAR_tf_state_file: ${{ vars.TF_STATE_FILE}}
      TF_VAR_instance_type: ${{ vars.INSTANCE_TYPE }}
      TF_VAR_ami: ${{ vars.AWS_AMI_ID }}
      TF_VAR_ssh_user: ${{ vars.SSH_USER }}
      

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6.0.1

      - name: AWS Login
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          terraform_version: 1.14.0

      - name: Terraform Init
        working-directory: ./terraform_infra
        run: |
            terraform init \
            -backend-config="region=${{ vars.AWS_REGION }}" \
            -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" \
            -backend-config="key=${{ vars.TF_STATE_FILE}}"

      
      - name: Terraform Validate
        working-directory: ./terraform_infra
        run: terraform validate

      - name: Terraform Check State
        working-directory: ./terraform_infra
        if: ${{ github.event.inputs.terra_op == 'check' }}
        run: terraform state list

      - name: Terraform Plan
        working-directory: ./terraform_infra
        if: ${{ github.event.inputs.terra_op == 'plan' }}
        run: terraform plan -out=tfplan


      - name: Terraform Apply
        id: apply_terraform
        working-directory: ./terraform_infra
        if: ${{ github.event.inputs.terra_op == 'apply' }}
        # generate .env file for application setup, to be used in provisioner script
        # apply terraform changes after that
        run: |
          echo "DB_URL=${{ secrets.DB_URL }}" >> ../setup/.env
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> ../setup/.env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> ../setup/.env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> ../setup/.env
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> ../setup/.env
          echo "REDIS_URL=${{ secrets.REDIS_URL }}" >> ../setup/.env
          echo "RABBIT_URL=${{ secrets.RABBIT_URL }}" >> ../setup/.env
        
          terraform plan -out=tfplan
          terraform apply -auto-approve tfplan
      
      - name: Revoke GitHub Actions runner IP from SG
        working-directory: ./terraform_infra
        if: ${{ github.steps.apply_terraform.conclusion == 'success' && github.event.inputs.terra_op == 'apply' }}
        run: |
          mv upload_sg.tf upload_sg.tf.ext
          mv final_sg.tf.ext final_sg.tf

          terraform plan -out=tfplan
          terraform apply -auto-approve tfplan


      - name: Terraform Destroy
        working-directory: ./terraform_infra
        if: ${{ github.event.inputs.terra_op == 'destroy' }}
        run: terraform destroy -auto-approve